server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

jwt:
  secret: CLOUD-NATIVE-MICROSERVICE-APP-KEY
  expiration: 3600000  # 1 hour in ms


  h2:
    console:
      enabled: true
      path: /h2-console


