server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://db.dndcwppfihrkwkbloowm.supabase.co:5432/postgres?currentSchema=auth
    username: postgres
    password: WpjZGgCm5uVYm21t


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: auth

jwt:
  secret: CLOUD-NATIVE-MICROSERVICE-APP-KEY
  expiration: 3600000  # 1 hour in ms





