server:
  port: 8082

spring:
  application:
    name: resource-monitoring-service

  config:
    import: configserver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8676/eureka/

management:
  endpoints:
    web:
      exposure: info,health
