server:
  port: 8082

spring:
  application:
    name: resource-monitoring-service

  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8676/eureka/
      register-with-eureka: true
      fetch-registry: true

management:
  endpoints:
    web:
      exposure: info,health
